import Field from './Field'
import HocField from './HocField'

export { Field, HocField }

export const Date = HocField('date')
export const DateRange = HocField('dateRange')
export const DateWeek = HocField('dateWeek')
export const DateWeekRange = HocField('dateWeekRange')
export const DateMonth = HocField('dateMonth')
export const DateMonthRange = HocField('dateMonthRange')
export const DateQuarter = HocField('dateQuarter')
export const DateQuarterRange = HocField('dateQuarterRange')
export const DateYear = HocField('dateYear')
export const DateYearRange = HocField('dateYearRange')
export const DateTime = HocField('dateTime')
export const DateTimeRange = HocField('dateTimeRange')
export const Time = HocField('time')
export const TimeRange = HocField('timeRange')
export const Select = HocField('select')
export const TreeSelect = HocField('treeSelect')
export const Cascader = HocField('cascader')
export const Radio = HocField('radio')
export const Checkbox = HocField('checkbox')
export const Switch = HocField('switch')
export const Slider = HocField('slider')
export const Number = HocField('number')
export const TextArea = HocField('textarea')
export const Password = HocField('password')
export const Text = HocField('text')
